import WBContractABI from "../json/WBContractABI.json";
import WRLDContractABI from "../json/WRLDContractABI.json";

// AGE VERIFICATION CONTRACT AND ABI

export const AGE_VERIFICATION_CONTRACT_ADDRESS = "0xF5c442c8ef7581B97935aA6FfCe8f55206fc39DE";
export const AGE_VERIFICATION_CONTRACT_ABI = WBContractABI.abi;
export const WRISTBAND_WRLD_PRICE = 2;

// WRLD TOKEN CONTRACT AND ABI

export const WRLD_CONTRACT_ADDRESS = "0xaD9B68D57eF0E3e873BE9cFe66f08A90B87Dc5E7";
export const WRLD_CONTRACT_ABI = WRLDContractABI.abi;